ALLOWED_TRANSITIONS = {
    "PO_DRAFT": ["PO_SUBMITTED", "PO_CANCELLED"],
    "PO_SUBMITTED": ["PO_APPROVED", "PO_REJECTED"],
    "PO_APPROVED": ["PO_CLOSED", "PO_CANCELLED"],
    "PO_REJECTED": [],
    "PO_CANCELLED": [],
    "PO_CLOSED": []
}

OPEN_STATUSES = {"PO_DRAFT", "PO_SUBMITTED", "PO_APPROVED"}
